### ISSUE TITLE
problem building from source on Arch

### ISSUE THREAD

**Issue by AladW** [ros-gbp/qt_gui_core-release#1]
Hi,
I'm trying to compile qt_qui_cpp from `release/indigo/qt_gui_cpp` (release 0.2.30-0) on Arch Linux, but get the following error:

```
[ 85%] Running SIP generator for qt_gui_cpp_sip Python bindings...
Traceback (most recent call last):
  File "/opt/ros/indigo/share/python_qt_binding/cmake/sip_configure.py", line 50, in <module>
    config = Configuration()
  File "/opt/ros/indigo/share/python_qt_binding/cmake/sip_configure.py", line 19, in __init__
    ['qmake', '-query'], env=env, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:90: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:375: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Full output: https://paste.xinu.at/WBf5/
The used build script is the following: https://paste.xinu.at/K6gZgV/

Ideas on how I could further troubleshoot this?

Regards,
Alad

**Comment by dirk-thomas** [comment]
The better repository to report issues is the actual source repository (https://github.com/ros-visualization/qt_gui_core). This is only the release repository. Also questions can be asked on http://answers.ros.org where more people will read it and potentially be able to help out.

Since the error message says `No such file or directory`when executing `qmake -query` have you checked that `qmake` is available?

**Comment by AladW** [comment]
Hi @dirk-thomas, sorry for replying late. In Arch the Qt4 qmake is in /usr/bin/qmake-qt4, so I guess that's why it was not recognized. /usr/bin/qmake is provided by Qt5, which results in warnings like

```
sip: Deprecation warning: /usr/share/sip/PyQt4/QtGui/qtoolbar.sip:45: SIP_SLOT_CON is deprecated
```

Linking qmake to qmake-qt4 results in

```
[ 85%] Compiling generated code for qt_gui_cpp_sip Python bindings...
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
In file included from /home/archie/.cache/aursync/ros-indigo-qt-gui-cpp/src/qt_gui_core-release-release-indigo-qt_gui_cpp-0.2.30-0/src/qt_gui_cpp_sip/../../include/qt_gui_cpp/plugin.h:37:0,
                 from plugin.sip:8:
/home/archie/.cache/aursync/ros-indigo-qt-gui-cpp/src/qt_gui_core-release-release-indigo-qt_gui_cpp-0.2.30-0/src/qt_gui_cpp_sip/../../include/qt_gui_cpp/plugin_context.h:43:19: fatal error: QWidget: No such file or directory
 #include <QWidget>
                   ^
compilation terminated.
make[3]: *** [Makefile:18: siplibqt_gui_cpp_sipcmodule.o] Error 1
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:61: devel/lib/python2.7/site-packages/qt_gui_cpp/libqt_gui_cpp_sip.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:375: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

https://paste.xinu.at/0Y9/

Feel free to close this issue if you want me to further refer to http://answers.ros.org (my bad on choosing the wrong channel)

Cheers

**Comment by dirk-thomas** [comment]
I don't have Arch available for testing your use case. The message seems to indicate that the include directories are not set correctly. Likely the location of the header files is different on your platform.

**Comment by AladW** [comment]
All right, thanks for the hints.
